### ISSUE TITLE
Protocol error: Connection closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by yidafu** [argos-ci/jest-puppeteer#334]
## 🐛 Bug Report

when `page` crashed, cause `teardown` failed. like this:

```log
yarn run v1.22.4
$ jest
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:248
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:249
    Error: Page crashed!
        at Page._onTargetCrashed (/mnt/d/Project/jest-page-closed/node_modules/puppeteer/lib/Page.js:213:24)
        at CDPSession.<anonymous> (/mnt/d/Project/jest-page-closed/node_modules/puppeteer/lib/Page.js:122:56)
        at CDPSession.emit (events.js:311:20)
        at CDPSession._onMessage (/mnt/d/Project/jest-page-closed/node_modules/puppeteer/lib/Connection.js:200:12)
        at Connection._onMessage (/mnt/d/Project/jest-page-closed/node_modules/puppeteer/lib/Connection.js:112:17)
        at WebSocket.<anonymous> (/mnt/d/Project/jest-page-closed/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
        at WebSocket.onMessage (/mnt/d/Project/jest-page-closed/node_modules/ws/lib/event-target.js:120:16)
        at WebSocket.emit (events.js:311:20)
        at Receiver.receiverOnMessage (/mnt/d/Project/jest-page-closed/node_modules/ws/lib/websocket.js:789:20)
        at Receiver.emit (events.js:311:20)

 FAIL  ./demo.spec.ts
  ● Test suite failed to run

    Protocol error: Connection closed. Most likely the page has been closed.

      at assert (node_modules/puppeteer/lib/helper.js:283:11)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        32.445s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

## To Reproduce

> In WSL `page.goto` seems always crashed. When I run the reproduce repo in git-bash, it is Ok.

Clone repo below.

Install dependencies.

**In WSL** run `yarn test`.

## Expected behavior

expect throw a **Page Crashed** error, not `teardown`  throw `Protocol error: Connection closed.` 

I think that should check whether page is closed and browser is conected, before close page and disconnect browser, 
## Link to repl or repo (highly encouraged)

<https://github.com/yidafu/jest-page-crashed-reproduce-repo>

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
 - Memory: 6.17 GB / 15.87 GB
 - Container: Yes
 - Shell: 4.4.20 - /bin/bash
## Binaries:
 - Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
 - Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
 - npm: 6.14.3 - ~/.nvm/versions/node/v12.16.1/bin/npm
## npmPackages:
 - expect-puppeteer: ^4.4.0 => 4.4.0
 - jest-puppeteer: ^4.4.0 => 4.4.0
```

similar issue:  https://github.com/smooth-code/jest-puppeteer/issues/292

**Comment by bogdancss** [comment]
any update on this?

**Comment by UziTech** [comment]
@bogdancss if you want to create a PR that would be very helpful 😁👍

**Comment by alexgbor** [comment]
I also have this issue. Any updates?

**Comment by gregberge** [comment]
I close it, let's open a new issue if you experience this problem.
