### ISSUE TITLE
Support for headless set to 'new' in jest-puppeteer.config.js

### ISSUE THREAD

**Issue by michaelbayday** [argos-ci/jest-puppeteer#526]
Currently getting the following error

```
 TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

      at new NodeEnvironment (node_modules/jest-environment-puppeteer/node_modules/jest-environment-node/build/index.js:86:49)
      at new PuppeteerEnvironment (node_modules/jest-environment-puppeteer/lib/env.js:94:1)
```

with the following jest-puppeteer.config.js

```js
const dotenv = require('dotenv');
const { resolve } = require('path');

dotenv.config();
module.exports = {
  launch: {
    args: ['--no-sandbox', '--window-size=1920,1080'],
    headless: 'new',
    slowMo: process.env.SLOWMO ? process.env.SLOWMO : 0,
    defaultViewport: {
      width: 1920,
      height: 1080,
    },
    userDataDir: resolve('./uploads/puppeteer-user-data'),
  },
  browserContext: 'incognito',
};

```

The new headless mode should be available per this document:
https://developer.chrome.com/articles/new-headless/

**Comment by tmcconechy** [comment]
@michaelbayday does this have anything to do with this warning?

```
 Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
```

Trying to figure out how to hide this warning now.

```
  launch: {
    headless: 'new',
   }
 ```

Doesnt work
