### ISSUE TITLE
Named exports moved from `jest-environment-puppeteer`

### ISSUE THREAD

**Issue by colinrotherham** [argos-ci/jest-puppeteer#534]
## 💥 Regression Report

The documentation for [**Create your own `globalSetup` and `globalTeardown`**](https://github.com/argos-ci/jest-puppeteer#create-your-own-globalsetup-and-globalteardown) needs a few tweaks

1. Named exports `{ setup, teardown }` have been removed
2. Setup export (default, not named) moved to `'jest-environment-puppeteer/setup'`
3. Teardown export (default, not named) moved to `'jest-environment-puppeteer/teardown'`

Users might assume that the CommonJS example still works as ESM:

**CommonJS**
```cjs
const { setup: setupPuppeteer } = require("jest-environment-puppeteer");
```

**ESM**
```mjs
import { setup as setupPuppeteer } from "jest-environment-puppeteer"
```

## Last working version

Worked up to version: v7.0.1

Stopped working in version: v8.0.0

## To Reproduce

Continue using `{ setup }` or `{ teardown }` named exports in ESM in v8.0.4

But since v8.0.0 it now crashes:

```console
file:///path/to/project/example.mjs:1
import { setup } from 'jest-environment-puppeteer'
         ^^^^^
SyntaxError: Named export 'setup' not found. The requested module 'jest-environment-puppeteer' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'jest-environment-puppeteer';
const { setup } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

It's also now mandatory for ~`jestConfig = {}`~ `jestConfig` in both global `teardown()` and `setup()`

```console
TypeError: Jest: Got error running globalSetup - /path/to/project/config/jest/browser/open.mjs, reason: Cannot read properties of undefined (reading 'maxWorkers')
    at getWorkersCount (/path/to/project/node_modules/jest-environment-puppeteer/dist/global-init.js:20:20)
    at startBrowsers (/path/to/project/node_modules/jest-environment-puppeteer/dist/global-init.js:50:26)
```

It was useful to omit the Jest config to ensure that watch mode stops the dev server

Otherwise it remains running after `Ctrl + C`

## Expected behavior

Update [**Create your own `globalSetup` and `globalTeardown`**](https://github.com/argos-ci/jest-puppeteer#create-your-own-globalsetup-and-globalteardown) documentation to show exports have now moved:

**Before** (v7.x)
```cjs
const { setup: setupPuppeteer } = require("jest-environment-puppeteer");
const { teardown: teardownPuppeteer } = require("jest-environment-puppeteer");
```

**After** (v8.x)
```cjs
const setupPuppeteer = require("jest-environment-puppeteer/setup");
const teardownPuppeteer = require("jest-environment-puppeteer/teardown");
```

## Link to repl or repo (highly encouraged)

The fix we needed for `jest-environment-puppeteer` via commit https://github.com/alphagov/govuk-frontend/pull/3368/commits/468496e8a958e2eef581a512d9e13d6024453b02

**Comment by gregberge** [comment]
Fixed in #536, also added in [release note](https://github.com/argos-ci/jest-puppeteer/releases/tag/v8.0.0).
