### ISSUE TITLE
Cannot find module 'node:stream' on fresh install

### ISSUE THREAD

**Issue by lucassardois** [argos-ci/jest-puppeteer#543]
## 🐛 Bug Report

After installing jest-puppeteer, the command `npx jest` throw the following error:
```
Error: Jest: Got error running globalSetup - /home/loustak/dev/puppeteer/node_modules/jest-environment-puppeteer/setup.js, reason: Cannot find module 'node:stream'
Require stack:
- /home/loustak/dev/puppeteer/node_modules/jest-dev-server/dist/index.js
- /home/loustak/dev/puppeteer/node_modules/jest-environment-puppeteer/dist/global-init.js
- /home/loustak/dev/puppeteer/node_modules/jest-environment-puppeteer/setup.js
- /home/loustak/dev/puppeteer/node_modules/jest-util/build/requireOrImportModule.js
- /home/loustak/dev/puppeteer/node_modules/jest-util/build/index.js
- /home/loustak/dev/puppeteer/node_modules/jest-config/build/getCacheDirectory.js
- /home/loustak/dev/puppeteer/node_modules/jest-config/build/Defaults.js
- /home/loustak/dev/puppeteer/node_modules/jest-config/build/normalize.js
- /home/loustak/dev/puppeteer/node_modules/jest-config/build/index.js
- /home/loustak/dev/puppeteer/node_modules/jest-cli/build/init/index.js
- /home/loustak/dev/puppeteer/node_modules/jest-cli/build/run.js
- /home/loustak/dev/puppeteer/node_modules/jest-cli/build/index.js
- /home/loustak/dev/puppeteer/node_modules/jest-cli/bin/jest.js
- /home/loustak/dev/puppeteer/node_modules/jest/bin/jest.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/loustak/dev/puppeteer/node_modules/jest-dev-server/dist/index.js:3:19)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.newLoader (/home/loustak/dev/puppeteer/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

## To Reproduce

1. `npm install --save-dev jest-puppeteer puppeteer jest`
2. `npx jest`

## Expected behavior

Test start without errors.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
 - CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
 - Memory: 3.10 GB / 31.10 GB
 - Container: Yes
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
 - npm: 7.24.2 - ~/.nvm/versions/node/v15.14.0/bin/npm
## npmPackages:
 - jest-puppeteer: ^8.0.5 => 8.0.5
```

**Comment by gregberge** [comment]
Hello @lucassardois, please upgrade your Node.js version to Node.js v16. The v15 is not supported by Jest Puppeteer, only [maitenance and LTS versions](https://github.com/nodejs/release#release-schedule) are suported.
