### ISSUE TITLE
Invariant: WORKERS_COUNT not found

### ISSUE THREAD

**Issue by pladaria** [argos-ci/jest-puppeteer#559]
After upgrading to version 8 or 9 I get the following error:

```
 FAIL   acceptance  app/__screenshot_tests__/page-screenshot-test.tsx
  ● Test suite failed to run

    Invariant: WORKERS_COUNT not found

      at readWorkersCount (node_modules/jest-environment-puppeteer/dist/index.js:95:15)
      at getWorkerWsEndpointIndex (node_modules/jest-environment-puppeteer/dist/index.js:116:21)
      at getWorkerWsEndpoint (node_modules/jest-environment-puppeteer/dist/index.js:120:19)
      at connectBrowserFromWorker (node_modules/jest-environment-puppeteer/dist/index.js:128:24)
      at connectBrowser (node_modules/jest-environment-puppeteer/dist/index.js:158:28)
      at initAll (node_modules/jest-environment-puppeteer/dist/index.js:216:11)
      at PuppeteerEnvironment.setup (node_modules/jest-environment-puppeteer/dist/index.js:254:15)
```

I can workaround that if I execute the test setting `WORKERS_COUNT=1` in the environment. But I'm unable to find any related documentation o mention to that in the Changelog.

Perhaps `jest-environment-puppeteer` should have some default for that value and don't fail, or document this somewhere.

**Comment by gregberge** [comment]
@pladaria it is very weird, what version of Jest do you use?

**Comment by pladaria** [comment]
I've prepared a repository to reproduce this issue:

STR:
* repo: https://github.com/pladaria/hello-world-web
* clone and install dependencies (yarn)
* run tests `yarn test:acceptance`. This should work
* upgrade `jest-environment-puppeteer` to latest version
* run tests `yarn test:acceptance`. You should get the `WORKERS_COUNT` error.

**Comment by gregberge** [comment]
Hi @pladaria, I try to run your repro but unfortunately for me it does not launch anything in both cases. I just have "listening" and nothing.

I gave a look and your config is very complicated, I think the problem is in : https://www.skypack.dev/view/@telefonica/acceptance-testing

You are the only one experiencing this issue so the problem is probably not in Jest Puppeteer itself.
